### ISSUE TITLE
Error in checktotalhours

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/lsf#309]
**[Original report](https://bitbucket.org/laborstudents/lsf-flask/issue/309) by Brian Ramsay (Bitbucket: [BrianRamsay](https://bitbucket.org/BrianRamsay), GitHub: [BrianRamsay](https://github.com/BrianRamsay)).**

----------------------------------------

A bad link was created and followed to check the hours:

`ERROR:flask.app:Exception on /laborstatusform/checktotalhours/202013/B00730365/NaN/275 [GET]`

Full stack trace:

```
[Tue Apr 13 21:47:18.387831 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468] Traceback (most recent call last):
[Tue Apr 13 21:47:18.387903 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
[Tue Apr 13 21:47:18.387951 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     response = self.full_dispatch_request()
[Tue Apr 13 21:47:18.388006 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
[Tue Apr 13 21:47:18.388044 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     rv = self.handle_user_exception(e)
[Tue Apr 13 21:47:18.388080 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
[Tue Apr 13 21:47:18.388116 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     reraise(exc_type, exc_value, tb)
[Tue Apr 13 21:47:18.388151 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
[Tue Apr 13 21:47:18.388187 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     raise value
[Tue Apr 13 21:47:18.388222 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
[Tue Apr 13 21:47:18.388263 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     rv = self.dispatch_request()
[Tue Apr 13 21:47:18.388298 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
[Tue Apr 13 21:47:18.388334 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Apr 13 21:47:18.388370 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]   File "/var/www/html/app/controllers/main_routes/laborStatusForm.py", line 166, in checkTotalHours
[Tue Apr 13 21:47:18.388405 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468]     totalHours = totalHours + item.formID.contractHours
[Tue Apr 13 21:47:18.388443 2021] [wsgi:error] [pid 18524] [remote 24.95.140.166:55468] TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

The fix is \(probably\) two-fold. 

1. See why NaN was built into the link and prevent that possibility, whether through code or data
2. Create a nicer error in the controller if it does happen

‌

**Comment by bryantal** [comment]
**Original comment by Hila Manalai (Bitbucket: [Hila Manalai](https://bitbucket.org/Hila Manalai), ).**

----------------------------------------

PR is in: [https://bitbucket.org/laborstudents/lsf-flask/pull-requests/292/fixes-the-error-in-checktotalhours](https://bitbucket.org/laborstudents/lsf-flask/pull-requests/292/fixes-the-error-in-checktotalhours)

**Comment by bryantal** [comment]
**Original comment by Alex Bryant (Bitbucket: [Alex Bryant](https://bitbucket.org/Alex Bryant), ).**

----------------------------------------

Issue resolved: https://bitbucket.org/laborstudents/lsf-flask/pull-requests/292/fixes-the-error-in-checktotalhours
